name: OuterLimits Daily

on:
  schedule:
    - cron: "55 7 * * 1-5"   # 08:55 UK weekdays
    - cron: "0 12 * * 1-5"   # 12:00 UK weekdays
    - cron: "0 16 * * 5"     # 17:00 UK Fridays (weekly wrap)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest  # <— use your self-hosted runner
    permissions:
      contents: write      # commit snapshots/README
    steps:
      - uses: actions/checkout@v4

      # Optional: still fine to use on self-hosted, ensures Node 20 is present
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Run watcher
        run: node index.js
        env:
          T212_BASE: ${{ secrets.T212_BASE }}
          T212_API_KEY: ${{ secrets.T212_API_KEY }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}

      - name: Commit snapshots (if changed)
        run: |
          git config user.name "outerlimits-bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore: update snapshots [ci skip]"
          git push
